import html as html_mod
from typing import List, Optional

from .decoder import DecodedSpd
from .timings import compute_profile_from_data


HTML_TEMPLATE = """<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>SPD Analyzer Report</title>
<style>
  :root {{
    --bg: #1a1a2e;
    --surface: #16213e;
    --primary: #0f3460;
    --accent: #e94560;
    --text: #eee;
    --text-dim: #aaa;
    --success: #4ade80;
    --fail: #f87171;
    --border: #334;
  }}
  * {{ margin: 0; padding: 0; box-sizing: border-box; }}
  body {{
    font-family: 'Segoe UI', system-ui, -apple-system, sans-serif;
    background: var(--bg);
    color: var(--text);
    padding: 2rem;
    max-width: 960px;
    margin: 0 auto;
  }}
  h1 {{
    text-align: center;
    font-weight: 300;
    font-size: 2.2rem;
    margin-bottom: 0.25rem;
    color: #7dd3fc;
  }}
  .subtitle {{
    text-align: center;
    color: var(--text-dim);
    margin-bottom: 2.5rem;
    font-size: 0.9rem;
  }}
  .module {{
    background: var(--surface);
    border: 1px solid var(--border);
    border-radius: 12px;
    padding: 1.5rem 2rem;
    margin-bottom: 2rem;
  }}
  .module h2 {{
    font-size: 1.3rem;
    font-weight: 600;
    margin-bottom: 1rem;
    padding-bottom: 0.5rem;
    border-bottom: 2px solid var(--accent);
    color: #fbbf24;
  }}
  .module.error h2 {{ color: var(--fail); }}
  .spec-grid {{
    display: grid;
    grid-template-columns: auto 1fr;
    gap: 0.3rem 1rem;
    margin: 1rem 0;
  }}
  .spec-label {{
    color: var(--text-dim);
    font-size: 0.85rem;
    white-space: nowrap;
  }}
  .spec-value {{
    font-weight: 500;
  }}
  .section-title {{
    font-size: 1rem;
    font-weight: 600;
    color: #7dd3fc;
    margin: 1rem 0 0.5rem;
    padding-top: 0.5rem;
    border-top: 1px solid var(--border);
  }}
  .profile-item {{
    display: inline-block;
    background: var(--primary);
    padding: 0.25rem 0.75rem;
    border-radius: 6px;
    margin: 0.2rem;
    font-size: 0.85rem;
    font-family: 'Consolas', 'Courier New', monospace;
  }}
  .crc-ok {{ color: var(--success); }}
  .crc-fail {{ color: var(--fail); }}
  .status-ok {{ color: var(--success); }}
  .status-fail {{ color: var(--fail); }}
  .overall {{
    text-align: center;
    font-size: 1.2rem;
    margin: 1rem 0;
    padding: 0.75rem;
    border-radius: 8px;
  }}
  .overall.ok {{ background: #14532d; color: var(--success); }}
  .overall.fail {{ background: #450a0a; color: var(--fail); }}
  footer {{
    text-align: center;
    color: var(--text-dim);
    font-size: 0.8rem;
    margin-top: 3rem;
  }}
</style>
</head>
<body>
<h1>SPD Analyzer</h1>
<p class="subtitle">Report generated by spd-analyzer v1.0</p>
{modules_html}
<footer>Based on JEDEC Standard 21-C — SPD Analyzer</footer>
</body>
</html>"""


def _build_module_html(decoded: DecodedSpd) -> str:
    error_class = " error" if decoded.error else ""
    parts = [f'<div class="module{error_class}">']

    if decoded.error:
        parts.append(f'<h2>{html_mod.escape(decoded.slot)}</h2>')
        parts.append(f'<p style="color: var(--fail);">Error: {html_mod.escape(decoded.error)}</p>')
        parts.append("</div>")
        return "\n".join(parts)

    p = decoded.parsed
    parts.append(f'<h2>{html_mod.escape(decoded.slot)} — {html_mod.escape(p.manufacturer_name) if p else ""}</h2>')

    parts.append('<div class="spec-grid">')

    specs = [
        ("Memory Type", p.memory_type if p else ""),
        ("Capacity", f"{p.module_capacity_mb} MB ({p.module_capacity_mb / 1024:.1f} GB)" if p else ""),
        ("Module Type", p.module_type if p else ""),
        ("Bus Width", f"{p.module_bus_width} bits" if p else ""),
        ("Ranks", str(p.ranks) if p else ""),
        ("Voltage", p.voltage_level if p else ""),
    ]

    for label, value in specs:
        parts.append(f'<div class="spec-label">{html_mod.escape(label)}</div>')
        parts.append(f'<div class="spec-value">{html_mod.escape(str(value))}</div>')

    parts.append("</div>")

    if p:
        crc_text = "Valid" if decoded.crc_base_valid else "Invalid"
        crc_class = "crc-ok" if decoded.crc_base_valid else "crc-fail"
        parts.append(f'<div class="spec-grid">')
        for label, value in [
            ("Manufacturer", p.manufacturer_name),
            ("Part Number", p.part_number),
            ("Serial", p.serial_number),
            ("SPD Revision", p.spd_revision),
            ("CRC", f'<span class="{crc_class}">{crc_text}</span>'),
        ]:
            parts.append(f'<div class="spec-label">{html_mod.escape(label)}</div>')
            parts.append(f'<div class="spec-value">{value}</div>')
        parts.append("</div>")

        if p.manufacturing_year or p.manufacturing_week:
            date_str = []
            if p.manufacturing_week:
                date_str.append(f"Week {p.manufacturing_week}")
            if p.manufacturing_year:
                date_str.append(str(p.manufacturing_year))
            parts.append(f'<div class="spec-label">Manufacture Date</div>')
            parts.append(f'<div class="spec-value">{" ".join(date_str)}</div>')
            parts.append("</div>")

        profiles = compute_profile_from_data(p)
        if profiles:
            parts.append('<div class="section-title">JEDEC Profiles</div>')
            parts.append('<div style="margin: 0.5rem 0;">')
            for prof in profiles:
                parts.append(
                    f'<span class="profile-item">{prof.speed_mts} MT/s — {prof.timing_string}</span>'
                )
            parts.append("</div>")

        parts.append('<div class="section-title">Organization</div>')
        parts.append('<div class="spec-grid">')
        for label, value in [
            ("Organization", p.module_organization),
            ("Chip Count", str(p.chip_count)),
            ("Chip Width", f"x{p.sdram_width_bits}"),
            ("Rows / Columns", f"{p.sdram_rows} / {p.sdram_columns}"),
        ]:
            parts.append(f'<div class="spec-label">{html_mod.escape(label)}</div>')
            parts.append(f'<div class="spec-value">{html_mod.escape(str(value))}</div>')
        parts.append("</div>")

    parts.append("</div>")
    return "\n".join(parts)


def export_html(results: List[DecodedSpd], filepath: str) -> str:
    modules_html = "\n".join(_build_module_html(r) for r in results)
    full_html = HTML_TEMPLATE.format(modules_html=modules_html)
    with open(filepath, "w") as f:
        f.write(full_html)
    return filepath
