create table if not exists shop(
    id bigint generated by default as identity,
    identifier varchar(255) not null,
    status varchar(50) not null,
    date_shop date,
    primary key (id)
);

create table if not exists shop_item(
    id bigint generated by default as identity,
    product_identifier varchar(100) not null,
    amount int not null,
    price float not null,
    shop_id bigint REFERENCES shop(id),
    primary key (id)
);