FROM node:latest
WORKDIR /chat-server-tcp
#ARG e usado somente no tempo de build da imagem
ARG PORT_BUILD=8000
#ENV e usado dentro do container 
ENV PORT=$PORT_BUILD
#expoe a porta a ser mapeada quando e dado um docker ps 
EXPOSE $PORT_BUILD
COPY . .
RUN npm install
ENTRYPOINT npm start